[package]
name = "richter"
version = "0.1.0"
authors = ["Cormac O'Brien <cormac@c-obrien.org>"]

[dependencies]
"arrayvec" = "0.3.20"
"bitflags" = "0.7.0"
"byteorder" = "1.0.0"
"env_logger" = "0.3.5"
"glium" = "0.16.0"
"nom" = "2.0.1"
"num" = "0.1.36"
"num-derive" = "0.1.36"
"lazy_static" = "0.2.2"
"log" = "0.3.6"
"rand" = "0.3.15"
"regex" = "0.2.1"
"rustc-serialize" = "0.3.22"
"time" = "0.1.36"

# binaries only
"docopt" = "0.7.0"
"pnet" = "0.17.0"
