[package]
name = "richter"
version = "0.1.0"
authors = ["Cormac O'Brien <cormac@c-obrien.org>"]

[dependencies]
"arrayvec" = "0.3.20"
"bitflags" = "0.7.0"
"byteorder" = "1.0.0"
"cgmath" = "0.15.0"
"env_logger" = "0.3.5"
"gfx" = "0.16.1"
"gfx_app" = "0.5.0"
"gfx_device_gl" = "0.14.4"
"gfx_window_glutin" = "0.18.0"
"glium" = "0.16.0"
"glutin" = "0.10.0"
"nom" = "2.0.1"
"num" = "0.1.36"
"num-derive" = "0.1.36"
"lazy_static" = "0.2.2"
"log" = "0.3.6"
"rand" = "0.3.15"
"regex" = "0.2.1"
"time" = "0.1.37"
"vulkano" = "0.7.2"
"vulkano-shader-derive" = "0.7.2"
"vulkano-win" = "0.7.2"
"winit" = "0.7"

# binaries only
"docopt" = "0.8"
"serde" = "1.0"
"serde_derive" = "1.0"
"pnet" = "0.20.0"
