[package]
name = "richter"
version = "0.1.0"
authors = ["Cormac O'Brien <cormac@c-obrien.org>"]

[dependencies]
"bitflags" = "0.7.0"
"byteorder" = "*"
"env_logger" = "0.3.4"
"glium" = "*"
"png" = "0.5.2"
"lazy_static" = "*"
"log" = "0.3"
"regex" = "*"
"time" = "0.1.35"
