[package]
name = "richter"
version = "0.1.0"
authors = ["Cormac O'Brien <cormac@c-obrien.org>"]

[dependencies]
"arrayvec" = "0.3.20"
"bitflags" = "0.7.0"
"byteorder" = "1.0.0"
"env_logger" = "0.3.4"
"glium" = "0.16.0"
"num" = "0.1.36"
"num-derive" = "0.1.36"
"png" = "0.5.2"
"lazy_static" = "0.2.2"
"log" = "0.3"
"regex" = "0.2"
"time" = "0.1.35"
