[package]
name = "richter"
version = "0.1.0"
authors = ["Cormac O'Brien <cormac@c-obrien.org>"]

[dependencies]
"bitflags" = "1.0.1"
"byteorder" = "1.2.1"
"cgmath" = "0.16.0"
"chrono" = "0.4.0"
"env_logger" = "0.5.3"
"gfx" = "0.17.1"
"gfx_device_gl" = "0.15"
"gfx_window_glutin" = "0.20.0"
"glutin" = "0.12"
"nom" = "2.0.1"
"num" = "0.1.42"
"num-derive" = "0.1.42"
"lazy_static" = "1.0.0"
"log" = "0.4.1"
"rand" = "0.4.2"
"regex" = "0.2.6"
"rodio" = "0.6.0"
"winit" = "0.10"

# binaries only
"docopt" = "0.8"
"serde" = "1.0"
"serde_derive" = "1.0"
"pnet" = "0.20.0"
