
# maybe add animations component 
# see https=//quakewiki.org/wiki/ogre.qc 
#figure out best way to parse this into memory ... group stuff up or no ?

 
classname="monster_ogre"

scripts = {

fn_prepare =  [

  #  { call="remove_self", conditions=[ {  gametype= "deathmatch"  }  ] },

    { call="precache_model", inputs={name="progs/ogre.mdl"} },
    { call="precache_model", inputs={name="progs/h_ogre.mdl"} },
    { call="precache_model", inputs={name="progs/grenade.mdl"} },
    
    { call="precache_sound", inputs={name="ogre/ogdrag.wav"} },
    { call="precache_sound", inputs={name="ogre/ogidle.wav"} },
    { call="precache_sound", inputs={name="ogre/ogidle2.wav"} },
    { call="precache_sound", inputs={name="ogre/ogpain1.wav"} },
    { call="precache_sound", inputs={name="ogre/ogsawatk.wav"} },
    { call="precache_sound", inputs={name="ogre/ogwake.wav"} },  

] 
fn_spawn =  [

    { call="register_component", inputs={ }}


    #{ name="model", inputs={model= "progs/ogre.mdl", size= 100} },
    # { name="stats", inputs={health= 200} },
    #{ name="movement", inputs={move_type= "step"} },
    # { name="collision", inputs={collision_type= "solid"} },




] 
 

}
